### ISSUE TITLE
problem in the file extract_vein_by_region_grow.py

### ISSUE THREAD

**Issue by koushikcsofficial** [ZhengPeng7/LeafVeinExtraction#1]
Traceback (most recent call last):
  File "E:\research\LeafVeinExtraction-master\main.py", line 93, in <module>
    extract_vein_by_region_grow.extract_vein_by_region_grow(edges_canny[i], images[i], 150, (15, 15))
  File "E:\research\LeafVeinExtraction-master\extract_vein_by_region_grow.py", line 164, in extract_vein_by_region_grow
    cv2.findContours(vein[:, round(w/2)-20:round(w/2)+20], cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

How to fix this? opencv-python 4.0.0.21

**Comment by yogeshry** [comment]
https://stackoverflow.com/questions/54164630/want-to-find-contours-valueerror-not-enough-values-to-unpack-expected-3-go

**Comment by ZhengPeng7** [comment]
Thanks for your answer. To be frank, I'm a bit confused... The number of parameters returned by findContours turns from 2(opencv2.x) --> 3(opencv3.x) --> 2(opencv4.x), maybe there was a protracted controversy in the comunity, haha.
