### ISSUE TITLE
Why can't most pictures output results when using pictures in leaves folder for testing

### ISSUE THREAD

**Issue by CBZ199671** [ZhengPeng7/LeafVeinExtraction#2]

**Comment by ZhengPeng7** [comment]
Sorry for the very very late reply, cuz I didn't receive the notification...
If you give some more details, though it's a very old project, maybe I can still try to solve the error you met.

**Comment by burhr2** [comment]
Hi, what he means is that the code works only with an example image you used. When trying with a new image the code crushes

**Comment by ZhengPeng7** [comment]
Haha, you know, that often happens XD. But to be serious, in such a traditional image processing method, I think adapting some thresholds may help. since most of them are not adaptive here.

**Comment by CBZ199671** [comment]
![error](https://user-images.githubusercontent.com/59392867/80364549-b3cae500-88b8-11ea-8e97-f3df177cc67c.png)
This is the error detail, when I use some of the images from leaves folder such as 7_98.JPG, an error occurred.

**Comment by burhr2** [comment]
> Haha, you know, that often happens XD. But to be serious, in such a traditional image processing method, I think adapting some thresholds may help. since most of them are not adaptive here.

Haha yeah a lot of things needs to be adjusted in order to adapt to a new dataset though It was a very good idea trying to prove it can be done to this extent

**Comment by ZhengPeng7** [comment]
> ![error](https://user-images.githubusercontent.com/59392867/80364549-b3cae500-88b8-11ea-8e97-f3df177cc67c.png)
> This is the error detail, when I use some of the images from leaves folder such as 7_98.JPG, an error occurred.

I think it's my fault that I didn't write some "if" for unexpected conditions. But the error should be caused by no `sub_vein_curvature` was detected, so `len(curvatures[idx_leaf]) == 1` here. Therefore the `np.hstack` cannot run properly -- when given an empty list.
